/*
 * This file is part of the libvirt-go-module project
 *
 * Permission is hereby granted, free of charge, to any person obtaining a copy
 * of this software and associated documentation files (the "Software"), to deal
 * in the Software without restriction, including without limitation the rights
 * to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
 * copies of the Software, and to permit persons to whom the Software is
 * furnished to do so, subject to the following conditions:
 *
 * The above copyright notice and this permission notice shall be included in
 * all copies or substantial portions of the Software.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 * IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 * FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
 * AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
 * LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
 * OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
 * THE SOFTWARE.
 *
 * Copyright (c) 2013 Alex Zorin
 * Copyright (C) 2016 Red Hat, Inc.
 *
 */

#ifndef LIBVIRT_GO_DOMAIN_COMPAT_H__
#define LIBVIRT_GO_DOMAIN_COMPAT_H__

/* 1.2.3 */

#ifndef VIR_DOMAIN_CORE_DUMP_FORMAT_RAW
#define VIR_DOMAIN_CORE_DUMP_FORMAT_RAW 0
#endif

#ifndef VIR_DOMAIN_CORE_DUMP_FORMAT_KDUMP_ZLIB
#define VIR_DOMAIN_CORE_DUMP_FORMAT_KDUMP_ZLIB 1
#endif

#ifndef VIR_DOMAIN_CORE_DUMP_FORMAT_KDUMP_LZO
#define VIR_DOMAIN_CORE_DUMP_FORMAT_KDUMP_LZO 2
#endif

#ifndef VIR_DOMAIN_CORE_DUMP_FORMAT_KDUMP_SNAPPY
#define VIR_DOMAIN_CORE_DUMP_FORMAT_KDUMP_SNAPPY 3
#endif

#ifndef VIR_MIGRATE_AUTO_CONVERGE
#define VIR_MIGRATE_AUTO_CONVERGE 1 << 13
#endif


/* 1.2.5 */

#ifndef VIR_DOMAIN_REBOOT_PARAVIRT
#define VIR_DOMAIN_REBOOT_PARAVIRT 1 << 4
#endif

#ifndef VIR_DOMAIN_SHUTDOWN_PARAVIRT
#define VIR_DOMAIN_SHUTDOWN_PARAVIRT 1 << 4
#endif

#ifndef VIR_DOMAIN_TIME_SYNC
#define VIR_DOMAIN_TIME_SYNC 1 << 0
#endif

/* 1.2.6 */

#ifndef VIR_DOMAIN_BLOCK_COMMIT_ACTIVE
#define VIR_DOMAIN_BLOCK_COMMIT_ACTIVE 1 << 2
#endif

#ifndef VIR_DOMAIN_BLOCK_JOB_TYPE_ACTIVE_COMMIT
#define VIR_DOMAIN_BLOCK_JOB_TYPE_ACTIVE_COMMIT 4
#endif

#ifndef VIR_DOMAIN_EVENT_ID_BLOCK_JOB_2
#define VIR_DOMAIN_EVENT_ID_BLOCK_JOB_2 16
#endif


/* 1.2.7 */

#ifndef VIR_DOMAIN_BLOCK_COMMIT_RELATIVE
#define VIR_DOMAIN_BLOCK_COMMIT_RELATIVE 1 << 3
#endif

#ifndef VIR_DOMAIN_BLOCK_REBASE_RELATIVE
#define VIR_DOMAIN_BLOCK_REBASE_RELATIVE 1 << 4
#endif


/* 1.2.8 */

#ifndef VIR_DOMAIN_BLOCK_COPY_SHALLOW
#define VIR_DOMAIN_BLOCK_COPY_SHALLOW 1 << 0
#endif

#ifndef VIR_DOMAIN_BLOCK_COPY_REUSE_EXT
#define VIR_DOMAIN_BLOCK_COPY_REUSE_EXT 1 << 1
#endif

#ifndef VIR_DOMAIN_STATS_STATE
#define VIR_DOMAIN_STATS_STATE 1 << 0
#endif

/* 1.2.9 */

#ifndef VIR_DOMAIN_BLOCK_COMMIT_BANDWIDTH_BYTES
#define VIR_DOMAIN_BLOCK_COMMIT_BANDWIDTH_BYTES 1 << 4
#endif

#ifndef VIR_DOMAIN_BLOCK_JOB_INFO_BANDWIDTH_BYTES
#define VIR_DOMAIN_BLOCK_JOB_INFO_BANDWIDTH_BYTES 1 << 0
#endif

#ifndef VIR_DOMAIN_BLOCK_JOB_SPEED_BANDWIDTH_BYTES
#define VIR_DOMAIN_BLOCK_JOB_SPEED_BANDWIDTH_BYTES 1 << 0
#endif

#ifndef VIR_DOMAIN_BLOCK_PULL_BANDWIDTH_BYTES
#define VIR_DOMAIN_BLOCK_PULL_BANDWIDTH_BYTES 1 << 6
#endif

#ifndef VIR_DOMAIN_BLOCK_REBASE_COPY_DEV
#define VIR_DOMAIN_BLOCK_REBASE_COPY_DEV 1 << 5
#endif

#ifndef VIR_DOMAIN_BLOCK_REBASE_BANDWIDTH_BYTES
#define VIR_DOMAIN_BLOCK_REBASE_BANDWIDTH_BYTES 1 << 6
#endif

#ifndef VIR_DOMAIN_JOB_STATS_COMPLETED
#define VIR_DOMAIN_JOB_STATS_COMPLETED 1 << 0
#endif

#ifndef VIR_DOMAIN_STATS_CPU_TOTAL
#define VIR_DOMAIN_STATS_CPU_TOTAL 1 << 1
#endif

#ifndef VIR_DOMAIN_STATS_BALLOON
#define VIR_DOMAIN_STATS_BALLOON 1 << 2
#endif

#ifndef VIR_DOMAIN_STATS_VCPU
#define VIR_DOMAIN_STATS_VCPU 1 << 3
#endif

#ifndef VIR_DOMAIN_STATS_INTERFACE
#define VIR_DOMAIN_STATS_INTERFACE 1 << 4
#endif

#ifndef VIR_DOMAIN_STATS_BLOCK
#define VIR_DOMAIN_STATS_BLOCK 1 << 5
#endif

#ifndef VIR_DOMAIN_UNDEFINE_NVRAM
#define VIR_DOMAIN_UNDEFINE_NVRAM 1 << 2
#endif

#ifndef VIR_MIGRATE_RDMA_PIN_ALL
#define VIR_MIGRATE_RDMA_PIN_ALL 1 << 14
#endif

#ifndef VIR_DOMAIN_EVENT_ID_TUNABLE
#define VIR_DOMAIN_EVENT_ID_TUNABLE 17
#endif


/* 1.2.11 */

#ifndef VIR_DOMAIN_EVENT_ID_AGENT_LIFECYCLE
#define VIR_DOMAIN_EVENT_ID_AGENT_LIFECYCLE 18
#endif

#if LIBVIR_VERSION_NUMBER < 1002011
typedef struct _virDomainFSInfo virDomainFSInfo;
typedef virDomainFSInfo *virDomainFSInfoPtr;
struct _virDomainFSInfo {
    char *mountpoint; /* path to mount point */
    char *name;       /* device name in the guest (e.g. "sda1") */
    char *fstype;     /* filesystem type */
    size_t ndevAlias; /* number of elements in devAlias */
    char **devAlias;  /* array of disk device aliases */
};
#endif

/* 1.2.12 */

#ifndef VIR_DOMAIN_DEFINE_VALIDATE
#define VIR_DOMAIN_DEFINE_VALIDATE 1 << 0
#endif

#ifndef VIR_DOMAIN_START_VALIDATE
#define VIR_DOMAIN_START_VALIDATE 1 << 4
#endif


/* 1.2.14 */

#ifndef VIR_DOMAIN_CONTROL_ERROR_REASON_NONE
#define VIR_DOMAIN_CONTROL_ERROR_REASON_NONE 0
#endif

#ifndef VIR_DOMAIN_CONTROL_ERROR_REASON_UNKNOWN
#define VIR_DOMAIN_CONTROL_ERROR_REASON_UNKNOWN 1
#endif

#ifndef VIR_DOMAIN_CONTROL_ERROR_REASON_MONITOR
#define VIR_DOMAIN_CONTROL_ERROR_REASON_MONITOR 2
#endif

#ifndef VIR_DOMAIN_CONTROL_ERROR_REASON_INTERNAL
#define VIR_DOMAIN_CONTROL_ERROR_REASON_INTERNAL 3
#endif

#ifndef VIR_DOMAIN_INTERFACE_ADDRESSES_SRC_LEASE
#define VIR_DOMAIN_INTERFACE_ADDRESSES_SRC_LEASE 0
#endif

#ifndef VIR_DOMAIN_INTERFACE_ADDRESSES_SRC_AGENT
#define VIR_DOMAIN_INTERFACE_ADDRESSES_SRC_AGENT 1
#endif

#ifndef VIR_DOMAIN_PAUSED_STARTING_UP
#define VIR_DOMAIN_PAUSED_STARTING_UP 11
#endif

#if LIBVIR_VERSION_NUMBER < 1002014
typedef struct _virDomainIOThreadInfo virDomainIOThreadInfo;
typedef virDomainIOThreadInfo *virDomainIOThreadInfoPtr;
struct _virDomainIOThreadInfo {
    unsigned int iothread_id;          /* IOThread ID */
    unsigned char *cpumap;             /* CPU map for thread. A pointer to an */
                                       /* array of real CPUs (in 8-bit bytes) */
    int cpumaplen;                     /* cpumap size */
};

typedef struct _virDomainInterfaceIPAddress virDomainIPAddress;
typedef virDomainIPAddress *virDomainIPAddressPtr;
struct _virDomainInterfaceIPAddress {
    int type;                /* virIPAddrType */
    char *addr;              /* IP address */
    unsigned int prefix;     /* IP address prefix */
};

typedef struct _virDomainInterface virDomainInterface;
typedef virDomainInterface *virDomainInterfacePtr;
struct _virDomainInterface {
    char *name;                     /* interface name */
    char *hwaddr;                   /* hardware address, may be NULL */
    unsigned int naddrs;            /* number of items in @addrs */
    virDomainIPAddressPtr addrs;    /* array of IP addresses */
};
#endif


/* 1.2.15 */

#ifndef VIR_DOMAIN_EVENT_ID_DEVICE_ADDED
#define VIR_DOMAIN_EVENT_ID_DEVICE_ADDED 19
#endif


/* 1.2.16 */

#ifndef VIR_DOMAIN_PASSWORD_ENCRYPTED
#define VIR_DOMAIN_PASSWORD_ENCRYPTED 1 << 0
#endif


/* 1.2.17 */

#ifndef VIR_DOMAIN_EVENT_WATCHDOG_INJECTNMI
#define VIR_DOMAIN_EVENT_WATCHDOG_INJECTNMI 6
#endif

/* 1.2.19 */

#ifndef VIR_DOMAIN_EVENT_DEFINED_RENAMED
#define VIR_DOMAIN_EVENT_DEFINED_RENAMED 2
#endif

#ifndef VIR_DOMAIN_EVENT_UNDEFINED_RENAMED
#define VIR_DOMAIN_EVENT_UNDEFINED_RENAMED 1
#endif

/* 1.3.2 */

#ifndef VIR_DOMAIN_EVENT_ID_MIGRATION_ITERATION
#define VIR_DOMAIN_EVENT_ID_MIGRATION_ITERATION 20
#endif


/* 1.3.3 */

#ifndef VIR_DOMAIN_EVENT_DEFINED_FROM_SNAPSHOT
#define VIR_DOMAIN_EVENT_DEFINED_FROM_SNAPSHOT 3
#endif

#ifndef VIR_DOMAIN_EVENT_RESUMED_POSTCOPY
#define VIR_DOMAIN_EVENT_RESUMED_POSTCOPY 3
#endif

#ifndef VIR_DOMAIN_EVENT_SUSPENDED_POSTCOPY
#define VIR_DOMAIN_EVENT_SUSPENDED_POSTCOPY 7
#endif

#ifndef VIR_DOMAIN_EVENT_SUSPENDED_POSTCOPY_FAILED
#define VIR_DOMAIN_EVENT_SUSPENDED_POSTCOPY_FAILED 8
#endif

#ifndef VIR_DOMAIN_PAUSED_POSTCOPY
#define VIR_DOMAIN_PAUSED_POSTCOPY 12
#endif

#ifndef VIR_DOMAIN_PAUSED_POSTCOPY_FAILED
#define VIR_DOMAIN_PAUSED_POSTCOPY_FAILED 13
#endif

#ifndef VIR_DOMAIN_RUNNING_POSTCOPY
#define VIR_DOMAIN_RUNNING_POSTCOPY 10
#endif

#ifndef VIR_DOMAIN_STATS_PERF
#define VIR_DOMAIN_STATS_PERF (1 << 6)
#endif

#ifndef VIR_MIGRATE_POSTCOPY
#define VIR_MIGRATE_POSTCOPY (1 << 15)
#endif

#ifndef VIR_DOMAIN_EVENT_ID_JOB_COMPLETED
#define VIR_DOMAIN_EVENT_ID_JOB_COMPLETED 21
#endif

/* 1.3.4 */

#ifndef VIR_DOMAIN_EVENT_ID_DEVICE_REMOVAL_FAILED
#define VIR_DOMAIN_EVENT_ID_DEVICE_REMOVAL_FAILED 22
#endif


/* 2.1.0 */

#ifndef VIR_DOMAIN_MEMORY_STAT_USABLE
#define VIR_DOMAIN_MEMORY_STAT_USABLE 8
#endif

#ifndef VIR_DOMAIN_MEMORY_STAT_LAST_UPDATE
#define VIR_DOMAIN_MEMORY_STAT_LAST_UPDATE 9
#endif


/* 2.3.0 */

#ifndef VIR_DOMAIN_UNDEFINE_KEEP_NVRAM
#define VIR_DOMAIN_UNDEFINE_KEEP_NVRAM (1 << 3)
#endif


/* 2.4.0 */

#ifndef VIR_DOMAIN_VCPU_HOTPLUGGABLE
#define VIR_DOMAIN_VCPU_HOTPLUGGABLE (1 << 4)
#endif

/* 3.0.0 */

#ifndef VIR_DOMAIN_EVENT_ID_METADATA_CHANGE
#define VIR_DOMAIN_EVENT_ID_METADATA_CHANGE 23
#endif

/* 3.2.0 */

#ifndef VIR_MIGRATE_TLS
#define VIR_MIGRATE_TLS 1 << 16
#endif

#ifndef VIR_DOMAIN_EVENT_ID_BLOCK_THRESHOLD
#define VIR_DOMAIN_EVENT_ID_BLOCK_THRESHOLD 24
#endif

/* 3.3.0 */

#ifndef VIR_DOMAIN_JOB_OPERATION_UNKNOWN
#define VIR_DOMAIN_JOB_OPERATION_UNKNOWN 0
#endif

#ifndef VIR_DOMAIN_JOB_OPERATION_START
#define VIR_DOMAIN_JOB_OPERATION_START 1
#endif

#ifndef VIR_DOMAIN_JOB_OPERATION_SAVE
#define VIR_DOMAIN_JOB_OPERATION_SAVE 2
#endif

#ifndef VIR_DOMAIN_JOB_OPERATION_RESTORE
#define VIR_DOMAIN_JOB_OPERATION_RESTORE 3
#endif

#ifndef VIR_DOMAIN_JOB_OPERATION_MIGRATION_IN
#define VIR_DOMAIN_JOB_OPERATION_MIGRATION_IN 4
#endif

#ifndef VIR_DOMAIN_JOB_OPERATION_MIGRATION_OUT
#define VIR_DOMAIN_JOB_OPERATION_MIGRATION_OUT 5
#endif

#ifndef VIR_DOMAIN_JOB_OPERATION_SNAPSHOT
#define VIR_DOMAIN_JOB_OPERATION_SNAPSHOT 6
#endif

#ifndef VIR_DOMAIN_JOB_OPERATION_SNAPSHOT_REVERT
#define VIR_DOMAIN_JOB_OPERATION_SNAPSHOT_REVERT 7
#endif

#ifndef VIR_DOMAIN_JOB_OPERATION_DUMP
#define VIR_DOMAIN_JOB_OPERATION_DUMP 8
#endif


/* 3.4.0 */

#ifndef VIR_DOMAIN_EVENT_SHUTDOWN_GUEST
#define VIR_DOMAIN_EVENT_SHUTDOWN_GUEST 1
#endif

#ifndef VIR_DOMAIN_EVENT_SHUTDOWN_HOST
#define VIR_DOMAIN_EVENT_SHUTDOWN_HOST 2
#endif


/* 3.5.0 */

#ifndef VIR_DOMAIN_BLOCK_COPY_TRANSIENT_JOB
#define VIR_DOMAIN_BLOCK_COPY_TRANSIENT_JOB 1 << 2
#endif


/* 3.9.0 */

#ifndef VIR_DOMAIN_LIFECYCLE_POWEROFF
#define VIR_DOMAIN_LIFECYCLE_POWEROFF 0
#endif

#ifndef VIR_DOMAIN_LIFECYCLE_REBOOT
#define VIR_DOMAIN_LIFECYCLE_REBOOT 1
#endif

#ifndef VIR_DOMAIN_LIFECYCLE_CRASH
#define VIR_DOMAIN_LIFECYCLE_CRASH 2
#endif

#ifndef VIR_DOMAIN_LIFECYCLE_ACTION_DESTROY
#define VIR_DOMAIN_LIFECYCLE_ACTION_DESTROY 0
#endif

#ifndef VIR_DOMAIN_LIFECYCLE_ACTION_RESTART
#define VIR_DOMAIN_LIFECYCLE_ACTION_RESTART 1
#endif

#ifndef VIR_DOMAIN_LIFECYCLE_ACTION_RESTART_RENAME
#define VIR_DOMAIN_LIFECYCLE_ACTION_RESTART_RENAME 2
#endif

#ifndef VIR_DOMAIN_LIFECYCLE_ACTION_PRESERVE
#define VIR_DOMAIN_LIFECYCLE_ACTION_PRESERVE 3
#endif

#ifndef VIR_DOMAIN_LIFECYCLE_ACTION_COREDUMP_DESTROY
#define VIR_DOMAIN_LIFECYCLE_ACTION_COREDUMP_DESTROY 4
#endif

#ifndef VIR_DOMAIN_LIFECYCLE_ACTION_COREDUMP_RESTART
#define VIR_DOMAIN_LIFECYCLE_ACTION_COREDUMP_RESTART 5
#endif

/* 4.2.0 */

#ifndef VIR_KEYCODE_SET_QNUM
#define VIR_KEYCODE_SET_QNUM 9
#endif

#ifndef VIR_DOMAIN_INTERFACE_ADDRESSES_SRC_ARP
#define VIR_DOMAIN_INTERFACE_ADDRESSES_SRC_ARP 2
#endif

/* 4.6.0 */

#ifndef VIR_DOMAIN_MEMORY_STAT_DISK_CACHES
#define VIR_DOMAIN_MEMORY_STAT_DISK_CACHES 10
#endif

/* 4.10.0 */

#ifndef VIR_DOMAIN_SHUTOFF_DAEMON
#define VIR_DOMAIN_SHUTOFF_DAEMON 8
#endif

#ifndef VIR_DOMAIN_STATS_IOTHREAD
#define VIR_DOMAIN_STATS_IOTHREAD (1 << 7)
#endif


/* 5.1.0 */

#ifndef VIR_DOMAIN_MIGRATE_MAX_SPEED_POSTCOPY
#define VIR_DOMAIN_MIGRATE_MAX_SPEED_POSTCOPY (1 << 0)
#endif

#ifndef VIR_DOMAIN_SNAPSHOT_XML_SECURE
#define VIR_DOMAIN_SNAPSHOT_XML_SECURE (1 << 0)
#endif

#ifndef VIR_DOMAIN_SAVE_IMAGE_XML_SECURE
#define VIR_DOMAIN_SAVE_IMAGE_XML_SECURE (1 << 0)
#endif

/* 5.2.0 */

#ifndef VIR_MIGRATE_PARALLEL
#define VIR_MIGRATE_PARALLEL (1 << 17)
#endif

/* 5.4.0 */

#ifndef VIR_DOMAIN_MEMORY_STAT_HUGETLB_PGALLOC
#define VIR_DOMAIN_MEMORY_STAT_HUGETLB_PGALLOC 11
#endif

#ifndef VIR_DOMAIN_MEMORY_STAT_HUGETLB_PGFAIL
#define VIR_DOMAIN_MEMORY_STAT_HUGETLB_PGFAIL 12
#endif


/* 5.6.0 */

#ifndef VIR_DOMAIN_UNDEFINE_CHECKPOINTS_METADATA
# define VIR_DOMAIN_UNDEFINE_CHECKPOINTS_METADATA (1 << 4)
#endif


/* 5.7.0 */

#ifndef VIR_DOMAIN_GUEST_INFO_USERS
#define VIR_DOMAIN_GUEST_INFO_USERS (1 << 0)
#endif

#ifndef VIR_DOMAIN_GUEST_INFO_OS
#define VIR_DOMAIN_GUEST_INFO_OS (1 << 1)
#endif

#ifndef VIR_DOMAIN_GUEST_INFO_TIMEZONE
#define VIR_DOMAIN_GUEST_INFO_TIMEZONE (1 << 2)
#endif

#ifndef VIR_DOMAIN_GUEST_INFO_HOSTNAME
#define VIR_DOMAIN_GUEST_INFO_HOSTNAME (1 << 3)
#endif

#ifndef VIR_DOMAIN_GUEST_INFO_FILESYSTEM
#define VIR_DOMAIN_GUEST_INFO_FILESYSTEM (1 << 4)
#endif

/* 5.10.0 */

#ifndef VIR_DOMAIN_AGENT_RESPONSE_TIMEOUT_BLOCK
#define VIR_DOMAIN_AGENT_RESPONSE_TIMEOUT_BLOCK -2
#endif

#ifndef VIR_DOMAIN_AGENT_RESPONSE_TIMEOUT_DEFAULT
#define VIR_DOMAIN_AGENT_RESPONSE_TIMEOUT_DEFAULT -1
#endif

#ifndef VIR_DOMAIN_AGENT_RESPONSE_TIMEOUT_NOWAIT
#define VIR_DOMAIN_AGENT_RESPONSE_TIMEOUT_NOWAIT 0
#endif

/* 6.0.0 */

#ifndef VIR_DOMAIN_JOB_STATS_KEEP_COMPLETED
#define VIR_DOMAIN_JOB_STATS_KEEP_COMPLETED (1 << 1)
#endif

#ifndef VIR_DOMAIN_BLOCK_JOB_TYPE_BACKUP
#define VIR_DOMAIN_BLOCK_JOB_TYPE_BACKUP 5
#endif

#ifndef VIR_DOMAIN_JOB_OPERATION_BACKUP
#define VIR_DOMAIN_JOB_OPERATION_BACKUP 9
#endif

#ifndef VIR_DOMAIN_BACKUP_BEGIN_REUSE_EXTERNAL
#define VIR_DOMAIN_BACKUP_BEGIN_REUSE_EXTERNAL (1 << 0)
#endif

#ifndef VIR_DOMAIN_STATS_MEMORY
#define VIR_DOMAIN_STATS_MEMORY (1 << 8)
#endif

/* 6.1.0 */

#ifndef VIR_DOMAIN_GET_HOSTNAME_LEASE
#define VIR_DOMAIN_GET_HOSTNAME_LEASE (1 << 0)
#endif

#ifndef VIR_DOMAIN_GET_HOSTNAME_AGENT
#define VIR_DOMAIN_GET_HOSTNAME_AGENT (1 << 1)
#endif

#ifndef VIR_DOMAIN_EVENT_CRASHED_CRASHLOADED
#define VIR_DOMAIN_EVENT_CRASHED_CRASHLOADED 1
#endif


/* 6.9.0 */

#ifndef VIR_DOMAIN_EVENT_MEMORY_FAILURE_RECIPIENT_HYPERVISOR
#define VIR_DOMAIN_EVENT_MEMORY_FAILURE_RECIPIENT_HYPERVISOR 0
#endif

#ifndef VIR_DOMAIN_EVENT_MEMORY_FAILURE_RECIPIENT_GUEST
#define VIR_DOMAIN_EVENT_MEMORY_FAILURE_RECIPIENT_GUEST 1
#endif


#ifndef VIR_DOMAIN_EVENT_MEMORY_FAILURE_ACTION_IGNORE
#define VIR_DOMAIN_EVENT_MEMORY_FAILURE_ACTION_IGNORE 0
#endif

#ifndef VIR_DOMAIN_EVENT_MEMORY_FAILURE_ACTION_INJECT
#define VIR_DOMAIN_EVENT_MEMORY_FAILURE_ACTION_INJECT 1
#endif

#ifndef VIR_DOMAIN_EVENT_MEMORY_FAILURE_ACTION_FATAL
#define VIR_DOMAIN_EVENT_MEMORY_FAILURE_ACTION_FATAL 2
#endif

#ifndef VIR_DOMAIN_EVENT_MEMORY_FAILURE_ACTION_RESET
#define VIR_DOMAIN_EVENT_MEMORY_FAILURE_ACTION_RESET 3
#endif


#ifndef VIR_DOMAIN_MEMORY_FAILURE_ACTION_REQUIRED
#define VIR_DOMAIN_MEMORY_FAILURE_ACTION_REQUIRED (1 << 0)
#endif

#ifndef VIR_DOMAIN_MEMORY_FAILURE_RECURSIVE
#define VIR_DOMAIN_MEMORY_FAILURE_RECURSIVE (1 << 1)
#endif


#ifndef VIR_DOMAIN_EVENT_ID_MEMORY_FAILURE
#define VIR_DOMAIN_EVENT_ID_MEMORY_FAILURE 25
#endif

#ifndef VIR_VCPU_INFO_CPU_OFFLINE
#define VIR_VCPU_INFO_CPU_OFFLINE -1
#endif

#ifndef VIR_VCPU_INFO_CPU_UNAVAILABLE
#define VIR_VCPU_INFO_CPU_UNAVAILABLE -2
#endif

#ifndef VIR_DOMAIN_AUTHORIZED_SSH_KEYS_SET_APPEND
#define VIR_DOMAIN_AUTHORIZED_SSH_KEYS_SET_APPEND (1 << 0)
#endif

#ifndef VIR_DOMAIN_AUTHORIZED_SSH_KEYS_SET_REMOVE
#define VIR_DOMAIN_AUTHORIZED_SSH_KEYS_SET_REMOVE (1 << 1)
#endif

/* 7.0.0 */

#ifndef VIR_DOMAIN_GUEST_INFO_DISKS
#define VIR_DOMAIN_GUEST_INFO_DISKS (1 << 5)
#endif

/* 7.1.0 */

#ifndef VIR_DOMAIN_MESSAGE_DEPRECATION
#define VIR_DOMAIN_MESSAGE_DEPRECATION (1 << 0)
#endif

#ifndef VIR_DOMAIN_MESSAGE_TAINTING
#define VIR_DOMAIN_MESSAGE_TAINTING (1 << 1)
#endif

/* 7.2.0 */

#ifndef VIR_DOMAIN_DIRTYRATE_UNSTARTED
#define VIR_DOMAIN_DIRTYRATE_UNSTARTED 0
#endif

#ifndef VIR_DOMAIN_DIRTYRATE_MEASURING
#define VIR_DOMAIN_DIRTYRATE_MEASURING 1
#endif

#ifndef VIR_DOMAIN_DIRTYRATE_MEASURED
#define VIR_DOMAIN_DIRTYRATE_MEASURED 2
#endif

#ifndef VIR_DOMAIN_STATS_DIRTYRATE
#define VIR_DOMAIN_STATS_DIRTYRATE (1 << 9)
#endif


#ifndef VIR_DOMAIN_NUMATUNE_MEM_RESTRICTIVE
#define VIR_DOMAIN_NUMATUNE_MEM_RESTRICTIVE 3
#endif

/* 7.4.0 */

#ifndef VIR_DOMAIN_CORE_DUMP_FORMAT_WIN_DMP
#define VIR_DOMAIN_CORE_DUMP_FORMAT_WIN_DMP 4
#endif

/* 7.9.0 */

#ifndef VIR_DOMAIN_EVENT_ID_MEMORY_DEVICE_SIZE_CHANGE
#define VIR_DOMAIN_EVENT_ID_MEMORY_DEVICE_SIZE_CHANGE 26
#endif

/* 7.10.0 */

#ifndef VIR_DOMAIN_GUEST_INFO_INTERFACES
#define VIR_DOMAIN_GUEST_INFO_INTERFACES (1 << 6)
#endif

/* 8.0.0 */

#ifndef VIR_DOMAIN_BLOCK_COPY_SYNCHRONOUS_WRITES
#define VIR_DOMAIN_BLOCK_COPY_SYNCHRONOUS_WRITES 1 << 3
#endif

#ifndef VIR_MIGRATE_NON_SHARED_SYNCHRONOUS_WRITES
#define VIR_MIGRATE_NON_SHARED_SYNCHRONOUS_WRITES 1 << 18
#endif


/* 8.1.0 */

#ifndef VIR_DOMAIN_SAVE_RESET_NVRAM
#define VIR_DOMAIN_SAVE_RESET_NVRAM 1 << 3
#endif

#ifndef VIR_DOMAIN_START_RESET_NVRAM
#define VIR_DOMAIN_START_RESET_NVRAM 1 << 5
#endif


#ifndef VIR_DOMAIN_DIRTYRATE_MODE_PAGE_SAMPLING
#define VIR_DOMAIN_DIRTYRATE_MODE_PAGE_SAMPLING 0
#endif

#ifndef VIR_DOMAIN_DIRTYRATE_MODE_DIRTY_BITMAP
#define VIR_DOMAIN_DIRTYRATE_MODE_DIRTY_BITMAP 1 << 0
#endif

#ifndef VIR_DOMAIN_DIRTYRATE_MODE_DIRTY_RING
#define VIR_DOMAIN_DIRTYRATE_MODE_DIRTY_RING 1 << 1
#endif

/* 8.3.0 */

#ifndef VIR_DOMAIN_DESTROY_REMOVE_LOGS
#define VIR_DOMAIN_DESTROY_REMOVE_LOGS 1 << 1
#endif

/* 8.5.0 */

#ifndef VIR_DOMAIN_ABORT_JOB_POSTCOPY
#define VIR_DOMAIN_ABORT_JOB_POSTCOPY (1 << 0)
#endif


#ifndef VIR_DOMAIN_EVENT_RESUMED_POSTCOPY_FAILED
#define VIR_DOMAIN_EVENT_RESUMED_POSTCOPY_FAILED 4
#endif

#ifndef VIR_DOMAIN_RUNNING_POSTCOPY_FAILED
#define VIR_DOMAIN_RUNNING_POSTCOPY_FAILED 11
#endif

#ifndef VIR_MIGRATE_POSTCOPY_RESUME
#define VIR_MIGRATE_POSTCOPY_RESUME 19
#endif

#ifndef VIR_MIGRATE_ZEROCOPY
#define VIR_MIGRATE_ZEROCOPY 20
#endif


/* 8.9.0 */

#ifndef VIR_DOMAIN_UNDEFINE_TPM
#define VIR_DOMAIN_UNDEFINE_TPM (1 << 5)
#endif

#ifndef VIR_DOMAIN_UNDEFINE_KEEP_TPM
#define VIR_DOMAIN_UNDEFINE_KEEP_TPM (1 << 6)
#endif

#ifndef VIR_DOMAIN_STATS_VM
#define VIR_DOMAIN_STATS_VM (1 << 10)
#endif

#endif /* LIBVIRT_GO_DOMAIN_COMPAT_H__ */
